config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  root 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users do
    put 'toggle_active' => 'users#toggle_active'
    put 'update_role' => 'users#update_role', on: :member
  end

  resources :students do
    put 'asist', to: 'asists#update'
    get 'delete_modal', to: 'students#delete_modal'
    resources :comments, only: [:create] do
      resources :answers, only: [:create]
      post 'toggle_like' => 'likes#toggle_like'
    end
  end


  resources :posts, only: [:create] do
    post 'answer' => 'answers#create_post_answer'
    post 'toggle_like' => 'likes#toggle_post_like'
  end

  get 'home', to: 'home#index'
end

app/models/student.rb
require 'date'

class Student < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :asist

  validates :first_name, :last_name, length: { minimum: 3 }, presence: true,
                                     format: { with: /\A[a-zA-Z\ñÑ\u00C0-\u017F\']+[\s?[a-zA-Z\ñÑ\u00C0-\u017F\']*]*\z/ }
  validates :birth_date, presence: true, format: { with: /^\d{4}-\d{2}-\d{2}$/, multiline: true }
  validates :attends, inclusion: { in: [true, false] }
  validates :address, presence: true
  validates :school_grade, presence: true

  validate :cant_be_future

  enum school_grade: %i[inicial primaria secundaria]

  def age
    (Date.today - birth_date.to_date).years
  end

  def cant_be_future
    unless (birth_date.present? && !birth_date.future?)
      errors.add(:birth_date, I18n.t('models.student.error_date'))
    else
      true
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include Pundit::Authorization
  before_action :set_student, only: %i[edit update destroy]

  def index
    authorize Student
    @presenter = StudentPresenter.new(params)
    @pagy, @students = @presenter.paginate
  end

  def show
    authorize Student
    @presenter = StudentPresenter.new(params)
    @student = @presenter.student
  end

  def new; end

  def delete_modal
    @student = Student.find(params[:student_id])
  end

  def create
    authorize Student
    @student = Student.new(student_params.merge(user: current_user))
    if @student.save
      redirect_to students_path, success: t('.created')
    else
      redirect_to students_path, warning: t('.not_created')
    end
  end

  def edit
    authorize @student
  end

  def update
    authorize @student
    if @student.update(student_params.merge(user: current_user))
      redirect_to students_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @student
    return redirect_to students_path, success: t('.deleted') if @student.destroy!

    redirect_to students_path, warning: t('.not_deleted')
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student)
          .except(:favourite_subjects, :subject_difficulty)
          .permit(:first_name, :last_name, :birth_date,
                  :address, :school_grade, :attends)
  end
end

app/views/students/_comment.html.erb
<section class='comments-main-section'>
  <div class='today-comments <%= comment[:highlight] ? 'highlight-container' : '' %> '>
    <div class='comment-nd'>
      <div class= "name-date"> 
        <h2 class='comment-name'><%= comment.name %></h2>
        <p class='comment-time'><%= comment.hour %></p>
      </div>
      <div class= "likes">
        <p> <%= comment.likes.count %> </p>
        <%= button_to student_comment_toggle_like_path(comment.student, comment) do %>
          <div class='<%= comment.likes.where(user_id: current_user.id).exists? ? 'liked' : '' %> '>
            <%= image_tag "Vector.svg", class:'comment-svg' %>
          </div>
        <% end %>
      </div>
    </div>
    <p class ="comment-p"><%= comment.user_comment %> </p>
    <div class="files">
      <% comment.files.each do |doc| %>
        <%= link_to doc.identifier, doc.url %>
      <% end %>
    </div>
    <details>
      <summary></summary>
      <% comment.answers.each do |answer| %>
        <div class="answer">
          <div class="comment-nd">
            <div class= "name-date"> 
              <h2 class='comment-name'><%= answer.user.first_name %></h2>
              <p class='comment-time'><%= answer.created_at.to_fs(:time) %></p>
            </div>
          </div>
          <p><%= answer.body %> </p>
        </div>
      <% end %>
      <%= form_with url:student_comment_answers_path(student, comment.id), method: :post do |form| %>
        <%= form.text_area :body, class: 'comment-area answer-input', placeholder: t('.post-placeholder') %>
          <%= image_submit_tag 'send.svg', class:'send-img' %>
      <% end %>
    </details>
  </div>
</section>

app/views/students/_post_comment.html.erb
<%= form_with url: student_comments_path(@student), scope: :comment, method: :post, data: { controller:"emoji-picker"} do |form| %>
  <div class="post-comment-container" data-controller='file'>
    <%= form.label :comment, t('.comments'), class: 'title-comments' %>
    <%= form.text_area :comment, size: "70x10", class:'comment-area', placeholder: t('.post-placeholder'), data: { emoji_picker_target: "input" } %>
    <div class='comment-container-bottom'>
      <div class='left-bottom-comment'>
        <%= image_tag("smile.svg", class: 'post-comment-svg', data: { action: "click->emoji-picker#toggle", emoji_picker_target: "button" }) %>        
        <%= form.label :files, class: 'label-files' do %>
          <%= image_tag("image.svg", class: 'post-comment-svg')%>
        <% end %>
        <%= form.file_field :files, data:{ file_target: 'files', action:'input->file#show' }, multiple: true%>
        <%= form.hidden_field :files_cache %>
        <div class= "highlight-comment">
          <%= form.check_box :highlight , class: 'highlight-checkbox' %>
          <%= form.label t('.highlight'), class: 'highlight-text' %>
        </div>
      </div>
      <%= form.submit t('.post-comment'), class:'post-comment-button '%>
    </div>
    <div data-file-target='fileName'>
    </div>
  </div>
<% end %>

app/views/students/_student.html.erb
<tr class='tr-row-data'>
  <td class='table-data td-link'> <%= link_to "#{student.full_name}", student_path(student.id), class: 'student-links'  %> </td>
  <td class='table-data'> <%= student.age %> </td>
  <td class='table-data'> <%= student.grade  %> </td>
  <td class='table-data'> <%= student.attendance  %> </td>
  <td> 
    <div class='table-button-center'>
      <% if policy(student).update? %>
        <%= link_to edit_student_path(student), data: { turbo_frame: 'modal' } do%>
          <div class="edit-icon">
          </div>
        <% end %> 
      <% end %>
    </div>
  </td> 
  <td>
    <div class='delete-button'>
      <% if policy(student).destroy? %>
        <%= link_to student_delete_modal_path(student.id), data: { turbo_frame: 'delete-modal' } do%>
          <div class="delete-icon table-button-center">
          </div>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/students/delete_modal.html.erb
<%= turbo_frame_tag "delete-modal" do %>
  <%= tag.div data: { controller: "turbo-delete-modal", turbo_delete_modal_target: "delete-modal", action: 
    "turbo:submit-end->turbo-delete-modal#submitEnd" } do %>
    <div class= 'close-delete-student'>
      <%= button_tag 'X', data: { action: "turbo-delete-modal#closeModal" }, type: "button", class: "close-modal"%>
    </div>
    
    <div class = "buttons-delete-modal">
    <h2 class = "h2_delete_modal"><%= t('.delete_modal') %></h2>
    <%= button_to t('.delete'),student_path(@student.id),method: :delete,  class:"button-delete-student"%>
    </div>

  <% end %>
<% end %>

app/views/students/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="container-modal">
  <%= tag.div data: { controller: "turbo-modal", turbo_modal_target: "modal", action: 
    "turbo:submit-end->turbo-modal#submitEnd 
    keyup@window->turbo-modal#closeWithKeyboard 
    click@window->turbo-modal#closeBackground" } do %>
    <h1 class='m-title'><%= t('.edit_student') %></h1>
    <%= form_with url: student_path(@student), scope: :student, method: :put do |form| %>
      <div class="m-login-form">
        <div class="m-item">
          <%= form.label :first_name,t('.name'), class: 'label-form'%>
          <%= form.text_field :first_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :last_name,t('.last_name'), class: 'label-form'%>
          <%= form.text_field :last_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :birth_date,t('.birth_date'), class: 'label-form'%>
          <%= form.date_field :birth_date, class: 'input-form' %>
        </div>
        <div class="m-item">
          <%= form.label :address, t('.address'), class: 'label-form' %>
          <%= form.text_field :address, class: 'input-form'%>
        </div>
        <div class='m-item'>
          <%= form.label :school_grade, t('.school_grade'), class: 'school-grade-form' %>
          <%= form.select :school_grade, Student.school_grades.keys, {} ,{ class: "input-form" } %>
        </div>
        <div class="school-attendance-form">
          <%= form.label :attends, t('.attendance'), class: 'label-form' %>
          <div class ="prueba">
            <div>
              <%= form.radio_button :attends, true %>
              <%= form.label :attends, t('.yes_'), class: 'radio-button-form' %>
            </div>
            <div>
              <%= form.radio_button :attends, false %>
              <%= form.label :attends, t('.no_'), class: 'radio-button-form' %>
            </div>
          </div>
        </div>

        <div class='m-item'>
          <%= form.label :favourite_subjects, t('.favourite_subjects'), class: 'school-grade-form' %>
          <%= form.text_field :favourite_subjects, class: 'input-form' %>
          <div class="school-subjects-edit">
            <p class= "school-subjects">Lengua x </p>
            <p class= "school-subjects">Historia x </p>
          </div>
        </div>

        <div class='m-item'>
          <%= form.label :subject_difficulty, t('.subject_difficulty'), class: 'school-grade-form' %>
          <%= form.text_field :subject_difficulty, class: 'input-form' %>
          <div class="school-subjects-edit">
            <p class= "school-subjects">Matemática x </p>
          </div>
        </div>


        <div>
          <%= form.submit :value => t('.save_changes'), class: 'm-login-button'%>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/students/index.html.erb
<div class='home-container' id='modal-background'>
  <div class="search-bar">
    <div class='button-filter'>
      <%= form_with(url: students_path, method: :get, scope: :user_filter) do |f| %> 
      <%= f.text_field :full_name , class: "filter"%>
      <div class="lupa-icon">
        <%= image_submit_tag("magnifying-glass-solid.svg")%>
      </div>
      <% end %> 
    </div>
    <%= link_to new_student_path, data: { turbo_frame: 'modal' } do%>
      <div class="create-user">  
        <div class="user-icon"></div>
          <p class= "button-new"><%=t('.new_student')%></p>
          <div class="button-new">
          </div>
      </div>
    <% end %>
  </div> 
  <div class='table-container'>
    <table class='table-class'>
      <thead>
        <tr>
          <th class='table-head'> <%= t('.students')%> </th> 
          <th class='table-head'> <%= t('.age') %> </th>
          <th class='table-head'> <%= t('.school_grade') %> </th>
          <th class='table-head'> <%= t('.attendance') %> </th>
          <th class='table-head'></th>
        <tr>
      </thead>
      <tbody>
        <%= render partial: "student", collection: @presenter.students %>
      </tbody>
    </table>
  </div> 
  <div class='pagination-var'>
    <%== pagy_nav(@presenter.pagynate) %>
  </div>
</div>

app/views/students/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", turbo_modal_target: "modal", action: 
    "turbo:submit-end->turbo-modal#submitEnd 
    keyup@window->turbo-modal#closeWithKeyboard 
    click@window->turbo-modal#closeBackground" } do %>
    <h1 class='m-title'><%= t('.new_student') %></h1>
    <%= form_with url: students_path, scope: :student, method: :post do |form| %>
      <div class="m-login-form">
        <div class="m-item">
          <%= form.label :name_user,t('.name'), class: 'label-form'%>
          <%= form.text_field :first_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :last_name,t('.last_name'), class: 'label-form'%>
          <%= form.text_field :last_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :birth_date,t('.birth_date'), class: 'label-form'%>
          <%= form.date_field :birth_date, class: 'input-form' %>
        </div>
        <div class="m-item">
          <%= form.label :address, t('.address'), class: 'label-form' %>
          <%= form.text_field :address, class: 'input-form'%>
        </div>
        <div class='m-item'>
          <%= form.label :school_grade, t('.school_grade'), class: 'school-grade-form' %>
          <%= form.select :school_grade, Student.school_grades.keys, class: 'input-form' %>
        </div>
        <div class="school-attendance-form">
          <%= form.label :attends, t('.attendance'), class: 'label-form' %>
          <div class ="prueba">
          <div>
          <%= form.radio_button :attends, true %>
          <%= form.label :attends, t('.yes_'), class: 'radio-button-form' %>
          </div>
          <div>
          <%= form.radio_button :attends, false %>
          <%= form.label :attends, t('.no_'), class: 'radio-button-form' %>
          </div>
          </div>
        </div>
        <div>
          <%= form.submit :value => t('.student_new'), class: 'm-login-button'%>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/students/show.html.erb
<body class="show-student-body">
  <div class='home-container-student' id='modal-background'>
    <div class='bread-crum-nav'>
      <%= link_to t('.students'), students_path, class: 'student-links' %>
      <p><strong>&nbsp;>&nbsp;</strong></p>
      <p class='student-links'> <%= @student.full_name %> </p>
    </div>
    <div class='show-container'>
      <aside left class='side-bar'>
      <section class='student-info vl'>
        <h1 class="profile-name"><%= @student.full_name %></h1>
        <div class='student-description'>
          <h2 class= "show-h2"><%= t('.student-data') %> </h2>
          <h3 class="title-info"><%= t('.birth_date')%> </h3>
          <p class="field-info"><%= @student.birth_date %> </p>
          <h3 class="title-info"><%= t('.address')%> </h3>
          <p class="field-info"><%= @student.address %></p>
          <h3 class="title-info"><%= t('.grade')%></h3>
          <p class="field-info"><%= @student.grade %></p>
          <h3 class="title-info"><%= t('.attendance')%></h3>
          <p class="field-info"><%= @student.attendance %></p>
          <h3 class="title-info"><%= t('.favorite-subjects')%></h3>
          <p class= "school-subjects"><%= t('.subject1')%></p>
          <h3 class="title-info"><%= t('.most-dificult-subject')%></h3>
          <p class= "school-subjects"><%= t('.subject2')%></p>
        </div>
        <div class='student-objectives'>
          <div class="obj-title">
            <h2><%= t('.objectives')%></h2>
            <div class="image">
              <%= image_tag 'plus-circle.png' %>
            </div>
          </div>
          <%=form_with url: students_path, scope: :student, method: :post do |form|%>
            <div class= "student-show-label"> 
              <%= form.check_box :alphabet %>
              <%= form.label :alphabet, t('.learn-alfabet')  %>
            </div>
            <div class= "student-show-label"> 
              <%= form.check_box :tables, class: 'remember-me'%>
              <%= form.label :tables, t('.learn-tables') %>
            </div>
          <%end%>
        </div>
      </section>
    </aside>
    <section class='comments-container'>
        <%= render partial: "post_comment", locals: {student: @student} %>
        <% @presenter.highlighted.each do |key, comments| %>
          <h3 class= "date-h3"> <%= (key.to_date == Date.today ) ? t('.today') : comments.first.format_date %> </h3>
          <%= render partial: "comment" , collection: comments, locals: { student: @student } %>
        <% end %>
        <% @presenter.not_highlighted.each do |key, comments| %>
          <h3 class= "date-h3"> <%= (key.to_date == Date.today ) ? t('.today') : comments.first.format_date %> </h3>
          <%= render partial: "comment" , collection: comments, locals: { student: @student } %>
        <% end %>
    </section>
  </div>
</body>