config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  root 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users do
    put 'toggle_active' => 'users#toggle_active'
    put 'update_role' => 'users#update_role', on: :member
  end

  resources :students do
    put 'asist', to: 'asists#update'
    get 'delete_modal', to: 'students#delete_modal'
    resources :comments, only: [:create] do
      resources :answers, only: [:create]
      post 'toggle_like' => 'likes#toggle_like'
    end
  end


  resources :posts, only: [:create] do
    post 'answer' => 'answers#create_post_answer'
    post 'toggle_like' => 'likes#toggle_post_like'
  end

  get 'home', to: 'home#index'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :students

  authenticates_with_sorcery!
  validates :first_name, :last_name, presence: true
  # validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/ }
  validates :email, presence: true
  validates_uniqueness_of :email

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true
  enum role: %i[administrador colaborador]
  # before_validation :set_default_role, on: :create
  attr_accessor :created_by

  private

  def set_default_role
    # Hacemos a todos admin para el deploy
    self.role ||= :administrador
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Pundit
  before_action :set_user, only: [:edit, :update, :update_role]

  def index
    authorize User
    @presenter = UserPresenter.new(params)
    @pagy, @users = pagy(@presenter.users)
  end

  def new
    authorize User
    @user = User.new
  end

  # Register from modal
  def create
    authorize User
    @user = User.new(register_params)
    if @user.save
      redirect_to users_path, success: t('.created')
    else
      redirect_to users_path, warning: t('.not_created')
    end
  end

  def edit
    authorize User
  end

  def update
    authorize User
    if @user.update(register_params)
      redirect_to users_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy; end

  def toggle_active
    authorize User
    @user = User.find(params[:user_id])
    @user.active = params[:user][:active]
    if @user.save
      flash[:success] = t('.modified')
    else
      flash[:warning] = t('.not_modified')
    end
  end

  def update_role
    authorize User
    if @user.update(user_params)
      redirect_to users_path, notice: t('.updated')
    else
      redirect_to users_path, notice: t('.not_updated')
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role)
  end

  def register_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
  end
end

app/views/users/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", turbo_modal_target: "modal", action: 
    "turbo:submit-end->turbo-modal#submitEnd 
    keyup@window->turbo-modal#closeWithKeyboard 
    click@window->turbo-modal#closeBackground" } do %>
    <h1 class='m-title'><%= t('.title-edit') %></h1>
    <%= form_with url: user_path(@user), scope: :user, method: :put do |form| %>
      <div class="m-login-form">
        <div class="m-item">
          <%= form.label :name_user,t('.first_name_edit'), class: 'label-form'%>
          <%= form.text_field :first_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :name_user,t('.last_name_edit'), class: 'label-form'%>
          <%= form.text_field :last_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :email, t('.email_edit'), class: 'label-form' %>
          <%= form.text_field :email, class: 'input-form', :readonly => true %>
        </div>
        <div class='m-item'>
          <%= form.label :role, 'Rol', class: 'label-form' %>
          <%= form.select :role, options_for_select(User.roles.keys, selected: @user.role), {}, { class: "input-form" } %>
        </div>
        <div>
          <%= form.submit :value => t('.search_edit'), class: 'm-login-button'%>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class='home-container' id='modal-background'>
  <div class="search-bar">
    <div class='button-filter'>
      <%= form_with(url: users_path, method: :get, scope: :user_filter) do |f| %> 
      <%= f.text_field :full_name , class: "filter"%>
      <div class="lupa-icon">
        <%= image_submit_tag("magnifying-glass-solid.svg")%>
      </div>
      <% end %> 
    </div>
    <%= link_to  new_user_path, data: { turbo_frame: 'modal' } do %>
      <div class="create-user">  
        <div class="user-icon"></div>
        <p class= "button-new"><%= t('.new-user') %> </p>
          <div class="button-new">
          </div>
      </div>
    <%end%>
  </div>
  <div class='table-container'> 
    <table class='table-class'>
      <thead>
        <tr>
          <th class='table-head'> <%= t('.users')%> </th> 
          <th class='table-head'> <%= t('.email')%> </th>
          <th class='table-head'> <%= t('.role') %> </th>
          <th class='table-head'> <%= t('.active') %> </th>
          <th class='table-head'> <%= t('.edit') %> </th>
          <th class='table-head'> <%= t('.menu') %> </th>
          <th class='table-head'></th>
          <th class='table-head'></th>
        <tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr class='tr-row-data'>
            <td class='table-data'> <%= user.first_name %> <%= user.last_name %> </td>
            <td class='table-data'> <%= user.email %> </td>
            <td class='table-data'>
              <%= user.role %>
            </td>         
            <%# Activate switch %>  
            <td>
              <div class='table-button-center'>
                <%= form_with(model: user, url: user_toggle_active_path(user), method: :put) do |form| %>
                  <div class="toggle-button" data-controller="users">
                    <%= form.check_box :active, data:{users_target:"checkbox", action:"users#toggleActive"} ,id:user.id   %>
                    <label class="" for=<%=user.id%>><%= form.submit %></label>
                  </div>
                <% end %>
              </div>
            </td>
            <td> 
              <div class='table-button-center'>
                <%= link_to edit_user_path(user), data: { turbo_frame: 'modal' } do%>
                  <div class="edit-icon"></div>
                <% end %> 
              </div>
            </td>
            <td>
              <div class='table-button-center'>
                <div class="menu-modal-icon"></div>
              </div>
            </td>
            <td>
              <div class="delete-button">
                <div class='delete-icon table-button-center'>
                  <%= link_to users_path(user.id), data: { turbo_frame: 'delete-modal' } do %>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class='pagination-var'>
    <%== pagy_nav(@pagy) %>
  </div>
</div>

app/views/users/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal", turbo_modal_target: "modal", action: 
    "turbo:submit-end->turbo-modal#submitEnd 
    keyup@window->turbo-modal#closeWithKeyboard 
    click@window->turbo-modal#closeBackground" } do %>
    <h1 class='m-title'><%= t('.title_new') %></h1>
    <%= form_with url: users_path, scope: :user, method: :post do |form| %>
      <div class="m-login-form">
        <div class="m-item">
          <%= form.label :name_user,t('.first_name_new'), class: 'label-form'%>
          <%= form.text_field :first_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :name_user,t('.last_name'), class: 'label-form'%>
          <%= form.text_field :last_name, class: 'input-form'%>
        </div>
        <div class="m-item">
          <%= form.label :email, t('.email'), class: 'label-form' %>
          <%= form.text_field :email, class: 'input-form'%>
        </div>
        <div class='m-item'>
          <%= form.label :password, t('.password'), class: 'label-form'%>
          <%= form.password_field :password,class: 'input-form'%>
          <% if @user.errors.include?(:password)%>
            <% @user.errors.full_messages_for(:password) do |error| %>
            <p><%= error %> </p>
            <% end %>
          <% end %>
        </div>
        <div class='m-item'>
          <%= form.label :confirm_password, t('.confirm-password'), class: 'label-form'%>
          <%= form.password_field :password_confirmation ,class: 'input-form' %>
        </div>
        <div>
          <%= form.submit :value => t('.search_new'), class: 'm-login-button'%>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>