config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  root 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users do
    put 'toggle_active' => 'users#toggle_active'
    put 'update_role' => 'users#update_role', on: :member
  end

  resources :students do
    put 'asist', to: 'asists#update'
    get 'delete_modal', to: 'students#delete_modal'
    resources :comments, only: [:create] do
      resources :answers, only: [:create]
      post 'toggle_like' => 'likes#toggle_like'
    end
  end


  resources :posts, only: [:create] do
    post 'answer' => 'answers#create_post_answer'
    post 'toggle_like' => 'likes#toggle_post_like'
  end

  get 'home', to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @presenter = PublicationPresenter.new(params)
  end
end

app/views/home/_post.html.erb
<section class='comments-main-section'>
  <div class='today-comments <%= post[:highlight] ? 'highlight-container' : '' %> '>
    <div class='comment-nd'>
      <div class= "name-date"> 
        <h2 class='comment-name'><%= post.name %></h2>
        <p class='comment-time'><%= post.hour %></p>
      </div>
      <div class= "likes">
        <p> <%= post.likes.count %> </p>
        <%= button_to post_toggle_like_path(post) do %>
          <div class='<%= 'liked' if post.decorate.like? %>'>
            <%= image_tag "Vector.svg", class:'comment-svg' %>
          </div>
        <% end %>
      </div>
    </div>
    <p class ="comment-p"><%= post.user_comment %></p>
    <div class="files">
      <% post.files.each do |doc| %>
        <%= link_to doc.identifier, doc.url %>
      <% end %>
    </div>
    <details>
      <summary></summary>
      <% post.answers.each do |answer| %>
        <div class="answer">
          <div class="comment-nd">
            <div class= "name-date"> 
              <h2 class='comment-name'><%= answer.user.first_name %></h2>
              <p class='comment-time'><%= answer.created_at.to_fs(:time) %></p>
            </div>
          </div>
          <p><%= answer.body %> </p>
        </div>
      <% end %>
      <%= form_with url: post_answer_path(post), method: :post do |form| %>
        <%= form.text_area :body, class: 'comment-area answer-input', placeholder: t('students.post_comment.post-placeholder') %>
          <%= image_submit_tag 'send.svg', class:'send-img' %>
      <% end %>
    </details>
  </div>
</section>

app/views/home/_student_asist.html.erb
<tr data-controller='asist' data-asist-url-value='<%= student_asist_path(student_asist.student) %>'>
  <td><%= student_asist.student.decorate.full_name%> </td>
  <td>
    <label class="radio-style">
      <span id="presente" class="dot"> 
        <%= radio_button_tag student_asist.id, :present, student_asist.present?,  data: {action: 'click->asist#change'}, class: 'radio-present' %>
      </span>
    </label>
  </td>
  <td>
    <label class="radio-style">
      <span class="dot">
        <%= radio_button_tag student_asist.id, :absent, student_asist.absent?,  data: {action: 'click->asist#change'}, class: 'radio-absent' %>
      </span>
    </label>
  </td>
  <td>
    <label class="radio-style">
      <span class="dot">
        <%= radio_button_tag student_asist.id, :retired, student_asist.retired?,  data: {action: 'click->asist#change'}, class: 'radio-retired'  %>
      </span>
    </label>
  </td>
</tr>

app/views/home/_submit_post.html.erb
<%= form_with url:posts_path(), scope: :comment, method: :post, data: { controller:"emoji-picker" } do |form| %>
  <div class="post-comment-container" data-controller='file'>
    <%= form.label :comment, t('.news'), class: 'title-comments' %>
    <%= form.text_area :comment, size: "70x10", class:'comment-area', placeholder: t('students.post_comment.post-placeholder'), data: { emoji_picker_target: "input" } %>
    <div class='comment-container-bottom'>
      <div class='left-bottom-comment'>
        <%= image_tag("smile.svg", class: 'post-comment-svg', data: { action: "click->emoji-picker#toggle", emoji_picker_target: "button" }) %>        
        <%= form.label :files, class: 'label-files' do %>
          <%= image_tag("image.svg", class: 'post-comment-svg')%>
        <% end %>
        <%= form.file_field :files, data:{ file_target: 'files', action:'input->file#show' }, multiple: true%>
        <%= form.hidden_field :files_cache %>
        <div class= "highlight-comment">
          <%= form.check_box :highlight , class: 'highlight-checkbox' %>
          <%= form.label t('students.post_comment.highlight'), class: 'highlight-text' %>
        </div>
      </div>
      <%= form.submit t('students.post_comment.post-comment'), class:'post-comment-button '%>
    </div>
    <div data-file-target='fileName'>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="home-date-container">
  <div class="date">
    <h3><%= I18n.l(Date.today,format:'%B %Y') %></h3>
    <h1><%= I18n.l(Date.today,format:'%A %d') %></h1>
  </div>
  <details open>
    <summary class="news"></summary>
    <div class='show-container'>
      <div class='comments-container home-box'>
        <section class='comment-main-section'>
          <%= render partial: "submit_post", locals: {} %>
          <% @presenter.highlighted.each do |key, posts| %>
            <h3 class= "date-h3"> <%= (key.to_date == Date.today ) ? t('.today') : posts.first.format_date %> </h3>
            <%= render partial: "post" , collection: posts %>
          <% end %>
          <% @presenter.not_highlighted.each do |key, posts| %>
            <h3 class= "date-h3"> <%= (key.to_date == Date.today ) ? t('.today') : posts.first.format_date %> </h3>
            <%= render partial: "post" , collection: posts %>
          <% end %>
      </div>
      <aside left class='side-bar'>
        <section class='home-box asist-container'>
          <h2 class="asist-title"><%=t('.assists')%></h2>
          <details open>
            <summary></summary>
            <table>
              <thead>
                <th class="asist-header" ><%=t('.student')%></th>
                <th class="asist-header">
                  <div class="tooltip"> 
                    P <span class="tooltip-text present"><%=t('.present students')%></span>
                  </div>
                </th>
                <th class="asist-header">
                  <div class="tooltip">
                    A <span class="tooltip-text ausent"><%=t('.absent students')%></span>
                  </div>
                </th>
                <th class="asist-header">
                  <div class="tooltip">
                    R <span class="tooltip-text retired"><%=t('.retired students')%></span>
                  </div>
                </th>
              </thead>
              <tbody>
                <%= render partial:'student_asist', collection: @presenter.asists %>
              </tbody>
            </table>
          </details>
        </section>
        <section class='home-box asist-container count-asist-container'>
          <details open>
            <summary></summary>
            <div class="asist-count">
              <div class="subtitle">
                <h3 class="asist-subtitle"><%=t('.asist')%></h3>
              </div>
              <div class="content-asist">
                <span class="circle green-line"><%= Asist.count_asists_type('present') %></span>
                <span class="circle orange-line"><%= Asist.count_asists_type('absent') %></span>
                <span class="circle yellow-line"><%= Asist.count_asists_type('retired') %></span>
              </div>
            </div>
            <div class="asist-count highlight-count">
              <div class="subtitle">
                <h3 class="asist-subtitle"><%=t('.highlighted')%></h3>
              </div>
              <div class="content-asist">
                <span class="square orange-line text-orange">3</span>
              </div>
            </div>
            <div class="asist-count highlight-count last-row">
              <div class="subtitle">
                <h3 class="asist-subtitle"><%=t('.equipment')%></h3>
              </div>
              <div class="content-asist">
                <p>Agustina Chirino</p>
                <p>Nicolas Garcia</p>
                <p>Eugenia Alonso</p>
              </div>
            </div>
          </details>
        </section>
      </aside>
    </div>
  </details>
</div>

app/views/home/login.html.erb
<div class="container">
    <div class='main-box'>
        <div class="navbar">
      <%= link_to t('.login'), '#', class: "link #{current_page?(root_url) ? 'link-active' : ''}" %>
      <%= link_to t('.registernav'), '/register', class: "link" %> 
      <hr id='line'>
    </div>
    <div class='section'>
      <div class='globe-photo'>
      </div>
      <div>
        <h1 class='title'><%= t('.title') %></h1>
        <%= form_with  do |form| %>
          <div class='login-form'>
            <div class="item">
              <%= form.label :email,t('.email'), class: 'label-form' %>
              <%= form.text_field :email, class: 'input-form', placeholder: 'admin@admin.com' %>
            </div>
            <div class="item">
              <%= form.label :password,t('.password'),  class: 'label-form'%>
              <%= form.password_field :password, class: 'input-form' %>
            </div>
            <div class='remember-me'>
              <%= form.check_box :remember_me, class: 'remember-me' %>
              <%= form.label :remember_me, t('.remember-me'),  class: 'remember-me-label' %>
            </div>
            <%= form.submit :value => t('.sign-in') , class: 'login-button'%> 
            <%= link_to t('.recover-password'),'/#', class:'recover-password' %> 
            <div class="login-google">
              <%= image_tag 'google.png'%>
              <%= link_to t('.google-login')%>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>