config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  root 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  get 'register' => 'user_registrations#new', :as => :new
  post 'register' => 'user_registrations#create'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users do
    put 'toggle_active' => 'users#toggle_active'
    put 'update_role' => 'users#update_role', on: :member
  end

  resources :students do
    put 'asist', to: 'asists#update'
    get 'delete_modal', to: 'students#delete_modal'
    resources :comments, only: [:create] do
      resources :answers, only: [:create]
      post 'toggle_like' => 'likes#toggle_like'
    end
  end


  resources :posts, only: [:create] do
    post 'answer' => 'answers#create_post_answer'
    post 'toggle_like' => 'likes#toggle_post_like'
  end

  get 'home', to: 'home#index'
end

app/views/partial/_navbar.html.erb
<div class='top-navbar' data-controller='modal-logout'>
  <div class='burger-menu'>
    <%= image_tag( "bars-solid.svg", class: 'menu-icon') %>
  </div>
  <div class="home-student">
    <div>
      <%= link_to home_path do %>
        <%= image_tag("home.svg", class: 'home-icon')%>
      <% end %>
    </div>
    <%= link_to students_path, class:'student' do %>
      <h1> <%=  t('students.index.students') %> </h1>
    <% end %>
  </div>
  <div class="logged-user">
    <span data-action="click->modal-logout#hideModal">
     <h1> <%= current_user.first_name %> <%= current_user.last_name %></h1>
    </span>
    <div class="hidden" data-modal-logout-target="hideButton">
      <%= button_to logout_path, class:'logout-btn', method: :delete do %>
        <span class="text-button"> <p><%= t('session.logout_button') %></p></span>
        <%= image_tag 'log-out.svg' %>
      <% end %>
    </div>
  </div>
</div>